# Base image for aarch64
FROM arm64v8/alpine:3.19.1 as base
RUN apk add --no-cache bash nodejs tini util-linux openssl procps coreutils curl tar jq

FROM base as build
RUN apk add --no-cache npm
COPY . /build
WORKDIR /build

# Build Cronicle without external plugins
RUN ./bundle /dist

FROM base

# Non-root user for security
ARG CRONICLE_UID=1000
ARG CRONICLE_GID=1099
RUN addgroup cronicle --gid $CRONICLE_GID && \
  adduser -D -h /opt/cronicle -u $CRONICLE_UID -G cronicle cronicle

# Copy built Cronicle files
COPY --from=build /dist /opt/cronicle

# Set environment variables
ENV PATH "/opt/cronicle/bin:${PATH}"
ENV CRONICLE_foreground=1
ENV CRONICLE_echo=1
ENV TZ=America/New_York

# Set working directory
WORKDIR /opt/cronicle

# Protect sensitive folders
RUN mkdir -p /opt/cronicle/data /opt/cronicle/conf && \
  chmod 0700 /opt/cronicle/data /opt/cronicle/conf

# Use tini as the entrypoint
ENTRYPOINT ["/sbin/tini", "--"]

# Default command to start Cronicle
CMD ["cronicle-start"]

