// Package sensordata writes hub/_data/live_sensors.yml from the most recent
// snapshot in the generate window so the Jekyll homepage Live Sensors panel
// always reflects the readings used for the last published post.
package sensordata

import (
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"HerbHub365/services/blog-poster/internal/config"
	"HerbHub365/services/blog-poster/internal/model"
	"gopkg.in/yaml.v3"
)

// Writer serialises sensor readings to a Jekyll _data YAML file.
type Writer struct {
	cfg config.SensorDataConfig
}

// NewWriter creates a Writer from the supplied config.
func NewWriter(cfg config.SensorDataConfig) *Writer {
	return &Writer{cfg: cfg}
}

// Write picks the most recent snapshot from the slice, maps it to the
// live_sensors schema, and atomically writes it to cfg.DataFilePath.
// It returns the absolute path of the written file so the caller can
// include it in the git commit alongside the blog post.
// Returns ("", nil) when the feature is disabled or there are no snapshots.
func (w *Writer) Write(snapshots []model.Snapshot) (string, error) {
	if !w.cfg.Enabled || len(snapshots) == 0 {
		return "", nil
	}

	latest := latestSnapshot(snapshots)
	doc := buildDocument(latest, w.cfg)

	data, err := yaml.Marshal(doc)
	if err != nil {
		return "", fmt.Errorf("marshal live_sensors yaml: %w", err)
	}

	header := "# live_sensors.yml — auto-generated by blog-poster after each publish\n" +
		"# Edit hub/_data/live_sensors.yml manually only when the service is stopped.\n\n"

	path, err := filepath.Abs(w.cfg.DataFilePath)
	if err != nil {
		return "", fmt.Errorf("resolve sensor data path: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("create _data dir: %w", err)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(header+string(data)), 0o644); err != nil {
		return "", fmt.Errorf("write live_sensors tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", fmt.Errorf("rename live_sensors tmp: %w", err)
	}

	return path, nil
}

// ── YAML document types ───────────────────────────────────────────────────────

type document struct {
	UpdatedAt string    `yaml:"updated_at"`
	Env       envBlock  `yaml:"env"`
	Herbs     []herbRow `yaml:"herbs"`
}

type envBlock struct {
	Temp          string `yaml:"temp"`
	Humidity      string `yaml:"humidity"`
	Light         string `yaml:"light"`
	ReservoirTemp string `yaml:"reservoir_temp"`
}

type herbRow struct {
	Name     string `yaml:"name"`
	Icon     string `yaml:"icon"`
	Temp     string `yaml:"temp"`
	Moisture string `yaml:"moisture"`
	Status   string `yaml:"status"`
}

// ── builders ─────────────────────────────────────────────────────────────────

func buildDocument(s model.Snapshot, cfg config.SensorDataConfig) document {
	ts := s.Timestamp.UTC()
	if ts.IsZero() && s.CollectedAt != nil {
		ts = s.CollectedAt.UTC()
	}
	if ts.IsZero() {
		ts = time.Now().UTC()
	}

	return document{
		UpdatedAt: ts.Format("15:04 — Jan 2, 2006"),
		Env:       buildEnv(s, cfg),
		Herbs:     buildHerbs(s, cfg),
	}
}

func buildEnv(s model.Snapshot, cfg config.SensorDataConfig) envBlock {
	// Reservoir temp lives in the Temperatures map under a dedicated key
	// (e.g. "water") configured via SENSOR_RESERVOIR_TEMP_KEY.
	var reservoirTemp *float64
	if cfg.ReservoirTempKey != "" {
		reservoirTemp = s.Temperatures[cfg.ReservoirTempKey]
	}

	return envBlock{
		Temp:          formatTemp(s.Environment.Temperature),
		Humidity:      formatPercent(s.Environment.Humidity),
		Light:         formatLux(s.Environment.LightLux),
		ReservoirTemp: formatTemp(reservoirTemp),
	}
}

func buildHerbs(s model.Snapshot, cfg config.SensorDataConfig) []herbRow {
	// Collect the union of soil moisture keys + temperature keys, minus
	// any key reserved for the water reservoir (e.g. "water").
	keys := make(map[string]struct{})
	for k := range s.SoilMoisture {
		keys[k] = struct{}{}
	}
	for k := range s.Temperatures {
		if k == cfg.ReservoirTempKey {
			continue
		}
		keys[k] = struct{}{}
	}

	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	rows := make([]herbRow, 0, len(sorted))
	for _, key := range sorted {
		moisture := s.SoilMoisture[key].Percent
		temp := s.Temperatures[key]

		rows = append(rows, herbRow{
			Name:     cfg.HerbDisplayName(key),
			Icon:     cfg.HerbIcon(key),
			Temp:     formatTemp(temp),
			Moisture: formatMoisturePercent(moisture),
			Status:   classifyStatus(moisture, cfg),
		})
	}
	return rows
}

// ── status classification ─────────────────────────────────────────────────────

func classifyStatus(moisture *float64, cfg config.SensorDataConfig) string {
	if moisture == nil {
		return "healthy"
	}
	v := *moisture
	if v < cfg.AlertBelow {
		return "alert"
	}
	if v < cfg.MonitorBelow {
		return "monitor"
	}
	return "healthy"
}

// ── formatting helpers ────────────────────────────────────────────────────────

func formatTemp(v *float64) string {
	if v == nil {
		return "–"
	}
	return fmt.Sprintf("%.1f°C", *v)
}

func formatPercent(v *float64) string {
	if v == nil {
		return "–"
	}
	return fmt.Sprintf("%.0f%%", *v)
}

func formatLux(v *float64) string {
	if v == nil {
		return "–"
	}
	return fmt.Sprintf("%d lux", int(math.Round(*v)))
}

func formatMoisturePercent(v *float64) string {
	if v == nil {
		return "–"
	}
	return fmt.Sprintf("%.0f%%", *v)
}

// ── snapshot selection ────────────────────────────────────────────────────────

func latestSnapshot(snapshots []model.Snapshot) model.Snapshot {
	latest := snapshots[0]
	latestTS := effectiveTime(latest)
	for _, s := range snapshots[1:] {
		if ts := effectiveTime(s); ts.After(latestTS) {
			latest = s
			latestTS = ts
		}
	}
	return latest
}

func effectiveTime(s model.Snapshot) time.Time {
	if !s.Timestamp.IsZero() {
		return s.Timestamp.UTC()
	}
	if s.CollectedAt != nil {
		return s.CollectedAt.UTC()
	}
	return time.Time{}
}

// ── display name / icon helpers ───────────────────────────────────────────────

// canonicalIcon maps common lowercase herb key substrings to their icon names.
var canonicalIcon = map[string]string{
	"basil":    "basil",
	"chilli":   "chilli",
	"chili":    "chilli",
	"oregano":  "oregano",
	"mint":     "mint",
	"thyme":    "thyme",
	"rosemary": "rosemary",
	"parsley":  "parsley",
	"cilantro": "cilantro",
	"dill":     "dill",
}

// DefaultIcon returns a best-effort icon name from the sensor key.
func DefaultIcon(key string) string {
	lower := strings.ToLower(key)
	for fragment, icon := range canonicalIcon {
		if strings.Contains(lower, fragment) {
			return icon
		}
	}
	return strings.ToLower(key)
}

// DefaultDisplayName title-cases the sensor key, replacing underscores/hyphens.
func DefaultDisplayName(key string) string {
	parts := strings.FieldsFunc(key, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}
