
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(\"rabbit.herbhub365.com\")"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  schedular:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    container_name: scheduler
    networks:
      - herbhub
    ports:
      - "3012:3012"
    volumes:
      - ./schedular/config:/opt/cronicle/config
      - ./schedular/data:/opt/cronicle/data
    environment:
      - CRONICLE_AdminEmail=andy@andy-barber.co.uk
    command: sh -c "bin/control.sh start && tail -f /dev/null"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cronicle.rule=Host(`scheduler.herbhub365.com`)"
      - "traefik.http.routers.cronicle.entrypoints=websecure"
      - "traefik.http.routers.cronicle.tls=true"
      - "traefik.http.services.cronicle.loadbalancer.server.port=3012"

  traefik:
    image: docker.io/library/traefik:v3.2.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      herbhub:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
      - /usr/share/certs/herbhub365:/etc/traefik/certs
    restart: unless-stopped

volumes:
  rabbitmq_data:
  scheduler:


networks:
  herbhub:
    external: true





