# docker/docker-compose.yml


networks:
  herbhub:
    driver: bridge
  ipvlan_herbhub:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    networks:
      - herbhub
      - herbhub-wifi
    environment:
      - TZ=Your/Timezone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
    deploy:
      restart_policy:
        condition: unless-stopped
    # Assign a static IP on IPvlan network
    networks:
      herbhub:
        ipv4_address: 172.18.0.2  # Example internal IP
      ipvlan_herbhub:
        ipv4_address: 192.168.1.200
    # Note: Assigning static IPs within Docker Compose requires the network to have IPAM configured
    # Alternatively, omit static IP and manage via external methods

volumes:
  rabbitmq_data:

networks:
  herbhub-wifi:
    external: true

