
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(\"rabbit.herbhub365.com\")"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  dashboard:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: dashboard
    networks:
      - herbhub
    volumes:
      - ./dashboard:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
  

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(\"dashboard.herbhub365.com\")"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.services.dashboard.loadbalancer.server.port=3000"


  schedular:
    image: soulteary/cronicle:0.9.63
    restart: always
    container_name: scheduler
    networks:
      - herbhub
    volumes:
      - ./scheduler/config:/opt/cronicle/config
      - ./scheduler/data:/opt/cronicle/data
      - ./scheduler/plugins:/opt/cronicle/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:3012/api/app/ping || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3
    logging:
        driver: "json-file"
        options:
            max-size: "10m"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cronicle.rule=Host(`scheduler.herbhub365.com`)"
      - "traefik.http.routers.cronicle.entrypoints=websecure"
      - "traefik.http.routers.cronicle.tls=true"
      - "traefik.http.services.cronicle.loadbalancer.server.port=3012"

  traefik:
    image: docker.io/library/traefik:v3.2.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      herbhub:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
      - /usr/share/certs/herbhub365:/etc/traefik/certs
    restart: unless-stopped

networks:
  herbhub:
    external: true





