
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    networks:
      herbhub-wifi:
        ipv4_address: 192.168.5.228
    networks:
      - herbhub
      - herbhub-wifi
    environment:
      - TZ=Your/Timezone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
    deploy:
      restart_policy:
        condition: unless-stopped

volumes:
  rabbitmq_data:

networks:
  herbhub:
    external: true
  herbhub-wifi:
    external: true




