cure
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(\"rabbit.herbhub365.com\")"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls=true"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"

  admin:
    build:
      context: ./admin
      dockerfile: dockerfile
    container_name: admin
    networks:
      - herbhub
    environment:
      RABBITMQ_URL: amqp://admin:yourpassword@rabbitmq:5672/
    volumes:
      - ./admin/frontend:/app/frontend # Serve frontend dynamically
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.herbhub365.com`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.services.admin.loadbalancer.server.port=8081"


  traefik:
    image: docker.io/library/traefik:v3.2.3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      herbhub:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik
      - /usr/share/certs/herbhub365:/etc/traefik/certs
    
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  herbhub:
    external: true




