version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - herbhub
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host('rabbit.herbbub365.com')"
      - "traefik.http.routers.nodered.entrypoints=websecure"
      - "traefik.http.services.nodered.loadbalancer.server.port=15672"  
      - "traefik.http.routers.nodered.tls=true"

  traefik:
    image: docker.io/library/traefik:v3.0.1
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      herbhub:

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik:/etc/traefik:ro
      - /var/lib/docker/data/certs/herbhub365.com:/etc/traefik/certs
    
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  herbhub:
    external: true




