

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      herbhub:
        ipv4_address: 172.18.0.2  # Static IP on herbhub network
    ports:
      - "5672:5672"      # AMQP protocol
      - "15672:15672"    # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: yourpassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    networks:
      herbhub:
        ipv4_address: 172.18.0.3      # Static IP on herbhub network
      herbhub-wifi:
        ipv4_address: 192.168.1.228   # Static IP on herbhub-wifi (ipvlan) network
    environment:
      - TZ=Your/Timezone  # Replace with your actual timezone, e.g., "America/New_York"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
    deploy:
      restart_policy:
        condition: unless-stopped

volumes:
  rabbitmq_data:

networks:
  herbhub:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

  herbhub-wifi:
    external: true  # This is your existing ipvlan network




