FROM golang:1.23-alpine AS builder

WORKDIR /src

ARG TARGETOS=linux
ARG TARGETARCH

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /out/data-collector ./cmd/data-collector

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /out/data-collector /usr/local/bin/data-collector

ENTRYPOINT ["/usr/local/bin/data-collector"]
