# docker/traefik/dynamic.yml

http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$apr1$...$..."

  routers:
    traefik-dashboard:
      rule: "Host(`traefik.herbhub365.local`)"
      service: api@internal
      entryPoints:
        - web
      middlewares:
        - auth
      tls:
        certResolver: myresolver


